"""Add pin and fav

Revision ID: da52d96752aa
Revises: 9c5e9605dde6
Create Date: 2026-08-07 16:02:14.442790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da52d96752aa'
down_revision: Union[str, None] = '9c5e9605dde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('notes', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_favorite')
    op.drop_column('notes', 'is_pinned')
    # ### end Alembic commands ###
